//
// Address.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Address: JSONEncodable {
    public var line1: String?
    public var line2: String?
    public var city: String?
    public var zip: Double?
    public var country: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["line1"] = self.line1
        nillableDictionary["line2"] = self.line2
        nillableDictionary["city"] = self.city
        nillableDictionary["zip"] = self.zip
        nillableDictionary["country"] = self.country
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
