//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class User: JSONEncodable {
    public var id: String?
    public var name: String?
    public var email: String?
    public var birthday: NSDate?
    public var address: Address?
    public var enrollments: [Channel]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["_id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["email"] = self.email
        nillableDictionary["birthday"] = self.birthday?.encodeToJSON()
        nillableDictionary["address"] = self.address?.encodeToJSON()
        nillableDictionary["enrollments"] = self.enrollments?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
