/**
 * IBM Personal Analytics - Services API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.*;
import java.util.Date;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class Channel  {
  
  @SerializedName("_id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("owner")
  private String owner = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("start_date")
  private Date startDate = null;
  @SerializedName("private")
  private Boolean _private = null;
  @SerializedName("tags")
  private List<String> tags = null;
  @SerializedName("status")
  private String status = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getOwner() {
    return owner;
  }
  public void setOwner(String owner) {
    this.owner = owner;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getStartDate() {
    return startDate;
  }
  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getPrivate() {
    return _private;
  }
  public void setPrivate(Boolean _private) {
    this._private = _private;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Channel channel = (Channel) o;
    return (id == null ? channel.id == null : id.equals(channel.id)) &&
        (name == null ? channel.name == null : name.equals(channel.name)) &&
        (owner == null ? channel.owner == null : owner.equals(channel.owner)) &&
        (description == null ? channel.description == null : description.equals(channel.description)) &&
        (startDate == null ? channel.startDate == null : startDate.equals(channel.startDate)) &&
        (_private == null ? channel._private == null : _private.equals(channel._private)) &&
        (tags == null ? channel.tags == null : tags.equals(channel.tags)) &&
        (status == null ? channel.status == null : status.equals(channel.status));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (owner == null ? 0: owner.hashCode());
    result = 31 * result + (description == null ? 0: description.hashCode());
    result = 31 * result + (startDate == null ? 0: startDate.hashCode());
    result = 31 * result + (_private == null ? 0: _private.hashCode());
    result = 31 * result + (tags == null ? 0: tags.hashCode());
    result = 31 * result + (status == null ? 0: status.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Channel {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  owner: ").append(owner).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  startDate: ").append(startDate).append("\n");
    sb.append("  _private: ").append(_private).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
