/**
 * IBM Personal Analytics - Services API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.Address;
import io.swagger.client.model.Channel;
import java.util.*;
import java.util.Date;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class User  {
  
  @SerializedName("_id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("birthday")
  private Date birthday = null;
  @SerializedName("address")
  private Address address = null;
  @SerializedName("enrollments")
  private List<Channel> enrollments = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getBirthday() {
    return birthday;
  }
  public void setBirthday(Date birthday) {
    this.birthday = birthday;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }
  public void setAddress(Address address) {
    this.address = address;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Channel> getEnrollments() {
    return enrollments;
  }
  public void setEnrollments(List<Channel> enrollments) {
    this.enrollments = enrollments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return (id == null ? user.id == null : id.equals(user.id)) &&
        (name == null ? user.name == null : name.equals(user.name)) &&
        (email == null ? user.email == null : email.equals(user.email)) &&
        (birthday == null ? user.birthday == null : birthday.equals(user.birthday)) &&
        (address == null ? user.address == null : address.equals(user.address)) &&
        (enrollments == null ? user.enrollments == null : enrollments.equals(user.enrollments));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (email == null ? 0: email.hashCode());
    result = 31 * result + (birthday == null ? 0: birthday.hashCode());
    result = 31 * result + (address == null ? 0: address.hashCode());
    result = 31 * result + (enrollments == null ? 0: enrollments.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  birthday: ").append(birthday).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  enrollments: ").append(enrollments).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
